name: remote ssh command
on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        env:
          host: ${{ secrets.HOST  }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: $host
          username: $username
          password: $password
          port: $port
          script: whoami
