name: Deploy to Hostinger

on:
  push:
    branches:
      - first-step
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEAutfmSGPoRXHFhzK+l1baSWWowsdihBhY5mmvSQW+DL0b79w/Ocfu
            LIz0vc23aH3YN/I6YZ4+IC6ZUCIoGshJQX/L/dZFG/J2pVEYSyOo2H0ucxlS/Q3eQx5DGy
            8eydZUTT4Yoxm29uoiXktj3sdyGv75zY/r37slBXO9q7y5ZbjBFNxaJwtW+mdcxiQzywew
            72CMgufmp5bmVNbs25hfj43ytyOUsLVG9Q23g73DUUUlW2zASVsC6/9TVyRgtgo0TxSd3c
            bIySsM9oVIzBDC1wHuhulRUIAc9ZjKUzn04ht7sB9l9dvERf4lh6tjP2hfhFQ+8C5eWJXT
            MBnq1zIeCOIRlIXJPrPP4/wH3/qoXOylJe4CkRik7W+y+vb/kuVa6S5Jl5NT3Bwa/Oltbn
            wfM8XeYHNy88uVfFCYTWnpGLj/EpYVZf9cNUudiXXI2J9tr6DcQtJUkwkFHTP/bBFcPzbm
            xbxEEPr/IYFEKRvXECvyxboXF2Q53tKRWuCH0uH3vnp14yIBf0z7s9vcaBhvLjf63RI22W
            xOvy6X/5+HFf9AiwQTHr1jfcPUddQ/JzERvV0VWG9zvRVCX0WDxD56FCUir0bgnr8kwrtJ
            k63BrCFpU7CFZYx0eQhfZ1P4zOhjvau5K8aw8k8E4XN4QZGMmNf0wIoPBJHq2gdSJOsQ3f
            8AAAdQ1CTQUtQk0FIAAAAHc3NoLXJzYQAAAgEAutfmSGPoRXHFhzK+l1baSWWowsdihBhY
            5mmvSQW+DL0b79w/OcfuLIz0vc23aH3YN/I6YZ4+IC6ZUCIoGshJQX/L/dZFG/J2pVEYSy
            Oo2H0ucxlS/Q3eQx5DGy8eydZUTT4Yoxm29uoiXktj3sdyGv75zY/r37slBXO9q7y5ZbjB
            FNxaJwtW+mdcxiQzywew72CMgufmp5bmVNbs25hfj43ytyOUsLVG9Q23g73DUUUlW2zASV
            sC6/9TVyRgtgo0TxSd3cbIySsM9oVIzBDC1wHuhulRUIAc9ZjKUzn04ht7sB9l9dvERf4l
            h6tjP2hfhFQ+8C5eWJXTMBnq1zIeCOIRlIXJPrPP4/wH3/qoXOylJe4CkRik7W+y+vb/ku
            Va6S5Jl5NT3Bwa/OltbnwfM8XeYHNy88uVfFCYTWnpGLj/EpYVZf9cNUudiXXI2J9tr6Dc
            QtJUkwkFHTP/bBFcPzbmxbxEEPr/IYFEKRvXECvyxboXF2Q53tKRWuCH0uH3vnp14yIBf0
            z7s9vcaBhvLjf63RI22WxOvy6X/5+HFf9AiwQTHr1jfcPUddQ/JzERvV0VWG9zvRVCX0WD
            xD56FCUir0bgnr8kwrtJk63BrCFpU7CFZYx0eQhfZ1P4zOhjvau5K8aw8k8E4XN4QZGMmN
            f0wIoPBJHq2gdSJOsQ3f8AAAADAQABAAACAAfc6h4FxlKV1SA5bHfl+c24738y8NxqQeOA
            cxX5nePfWXugozCFT2qki/Ao5h0Jnr3L/dT52dd03pLWvSVTZHHTNPx7tfDVJVUTspgG6i
            YiLoA9gpaPrNjaPyy3sO4BjQ6rHFJQ1LhTZhrdxVgswIqOTGjwM5b4wzgVhNfjW1ICkm2U
            UF7wRTrIeskD4QIcUr/gKkmgBL7sxMixOsqLAQqDiMFYR/ufxVqutxheNggHhujwDK+Jmv
            ffiNxT9ZXzm/vv/CzHHtAIdcUyGrwrwGdX93fJ/dgLbCyRv4H9IGcbjPr+d0X/d6USavXo
            qoaSl+JzwSpOaT4FIBwYGx/vRgA7SkOyQDDNDNIOD+vDfXoU80+2arCb8/wd0D+pNucKlm
            6RTcHip5s+tP0JsDkXWvcmJ4G70UmPa1nw5UN2ODFo95T7gKEPhdQrNDwfKUahTJAhE/wO
            SnAvleyLNEiS2mKn4I2BwZNDOKwIKcDB6KkqJbQRK1FyyuFCSsBwvAhxhHVYMiYMT1HJsh
            oCU+yIeBVpcgRVGLDihUxMXlLsYL2K0Zdrb5G0jp3UP+QvIhYDAU5nW7uUXXFvie+Ob9Ld
            mcWAqd00J7hxJEXxgO7RgvXg9CENQWrD9FHuIfo2LsezCzGQlfJm+m0w0yylIZxuQG/TQC
            GWatzH71cSY6puGb0xAAABAQCJqhOHgC25T8+SI8/77lV9Us0PUy4TNh8dJxWAoYI9eFDM
            P3vmBTnydrOkdOllFCjWH1I2T5hPJtCFj3chFeL/AwWvbwsKJEvvvYv3GTKpOmJOE/874t
            vbyDMlNXVeDo0LIu9IK7AZVQRSP7RrP+/XCBWxAoUJwoBkdI6G1IqBmCb5ttdmmKk238Jk
            ZMwqjKMTRJrITbYQP32FPlNLfMt9qySPbSL9QwWrOE3uf5GOX7TgBM8nLTl5M0Ep6ic7Va
            cg7YoFLJdgY7PwY9/w5FFkxLCsejnZtSozftL/wgBVjgorwnC7ve8QLV+cV806UZqpYGjf
            lfKNtKeY4FAlZSFMAAABAQDeT7cUGpXGyP/Jrz/PX94FmbBpzuxGW4lQJxve5BPKr0UA4n
            w9FbxP/WgaXDX5wDSWCGwG27DVfsuEsI0fsP1Mp+cWSvaM9BvPZ9/K5HkYz1EpAZPnS7IA
            FBgFc+MpXtrcDP/a+EbefR18zG2C+crq93DJE8sSjtqZObfRxkL6F42vKymro2Hzii4JSD
            7Da96vTZNVm3prWUN98gFbrC1jNIyiGsx247ehBlTwHHEDR0+SvU/eciU8AnEDlqLP79gQ
            4yIk0R6gqBRAm789TKOYYj3O1NgLY1AYekhMvtkX5WFvRFVps9UHpjS8KuGHzl4qkcccZ3
            wCorrioyySWgSlAAABAQDXKD9qRGAKBazLIbEd/MspYAzW9epgnmiY7BUqbwL1CLnsBtV/
            URGo0muIl42ShEOVsTVGoAtjiFzdDuNsmE3PYZIO9OUhMtlXyU+Ab5+0XITt6W3q/SOtmH
            UE4m+NrcwasSyyafRdHgYq6l+8YDvlkMDnaqSsmh5Ka55HVTlAtuXrdHihfsdNkpgpR5jd
            xg9YdotZwCFCGioJ4mR9EGGA1oG4wjGXOTG6UJgp6W193ZrW9HFCYoRD3c9oCldSQ2cbjA
            xLvoFWq4xXguqsz67g1ePQwLOee7qftNKHaaxb0+J5w3UvzQR45vwkb5LqqQ8Um4RsUCuq
            MEQccl/00sLTAAAAF3RjaGVwZ2FwYXRyaWNrQHlhaG9vLmZyAQID
            -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Transfer files to Hostinger instance
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  -P 65002 -r $PWD u256492878@149.100.151.80:~/public_html/tontine-api

      - name: Connect to Hostinger instance and deploy
        run: |
          ssh -i ~/.ssh/id_rsa -p 65002  u256492878@149.100.151.80 << EOF

            # access to the directory of the project
            cd ~/public_html/tontine-api

            # delete cache directory
            rm -rf var

            # use the current composer.phar (should setup composer each time)
            cp ~/public_html/composer.phar ~/public_html/tontine-api

            # Stop the currently running Symfony process (if any)
            #if [ -f ./var/run/symfony.pid ]; then
            #    kill \$(cat ./var/run/symfony.pid)
            #    rm ./var/run/symfony.pid
            #fi

            # Install dependencies
            php composer.phar install
            # composer install --no-dev --optimize-autoloader

            # start docker postgresql daemon and migrate the database changes
            bin/console doctrine:migrations:migrate

            # Clear cache
            php bin/console cache:clear  --no-warmup
            php bin/console cache:warmup

            exit
          EOF
